# Generated by Django 3.2 on 2021-06-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpverify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
