# Generated by Django 3.2 on 2021-06-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpverify', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
